In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

In [2]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB

In [4]:
X, y = load_iris(return_X_y=True)

In [5]:
X.shape

(150, 4)

In [6]:
x_train = X[0:140]
y_train = y[0:140]

In [7]:
ingenuo1 = GaussianNB()

In [8]:
ingenuo1.fit(x_train, y_train)

GaussianNB()

In [9]:
ingenuo1.class_prior_

array([0.35714286, 0.35714286, 0.28571429])

In [10]:
x_test = X[140:,:]
y_test = y[140:]

In [11]:
ingenuo1.predict(x_test)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
ingenuo1.predict_proba(x_test)
# Cada columna es la probabilidad de una de las 3 categorias. 1, 2 y 3

array([[1.45570357e-222, 9.10100515e-009, 9.99999991e-001],
       [6.72516262e-187, 8.12393208e-007, 9.99999188e-001],
       [1.38739746e-152, 3.24474447e-002, 9.67552555e-001],
       [1.11161794e-233, 6.95154749e-009, 9.99999993e-001],
       [6.69421989e-237, 3.08738958e-010, 1.00000000e+000],
       [2.77659905e-191, 1.03842284e-006, 9.99998962e-001],
       [1.33268444e-149, 3.19729441e-002, 9.68027056e-001],
       [1.22674793e-167, 5.68436987e-004, 9.99431563e-001],
       [2.51929644e-199, 4.29286712e-007, 9.99999571e-001],
       [4.34063154e-146, 7.45723204e-002, 9.25427680e-001]])