In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = pd.read_csv('/kaggle/input/sms-spam-collection-dataset/spam.csv', encoding='latin-1')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
df = df[['v1','v2']]
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# Replace special characters with nothing and apply lowercase in string fir each row
special_char = '@_!#$%^&*()<>?/\|}{~:.,;[]'
for i, row in df.iterrows():
    df.iloc[i, 1] = ''.join(x for x in df.iloc[i, 1] if not x in special_char)
    df.iloc[i, 1] = df.iloc[i, 1].lower()
df.head()

v1                                                 v2
0   ham  go until jurong point crazy available only in ...
1   ham                            ok lar joking wif u oni
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham        u dun say so early hor u c already then say
4   ham  nah i don't think he goes to usf he lives arou...

In [5]:
# Get uniques words from all text in sms dataframe
all_words = []
for i, row in df.iterrows():
    list_words = df.iloc[i, 1].split(' ')
    all_words = all_words + list_words
all_words = pd.DataFrame(all_words)
print('n all words:', all_words.shape[0])
uniques_words = all_words[0].unique()
print('n uniques words:', uniques_words.shape[0])

n all words: 86961
n uniques words: 9877


In [6]:
# Create X df with the count for each word from the sms text
y = df.iloc[:,0]
X = pd.DataFrame(0, index=df.index, columns=uniques_words)
for i, row in df.iterrows() :
    list_words = row[1].split(' ')
    for word in list_words :
        X.loc[i,[word]] = X.loc[i,[word]] + [1 for col in X.columns if word == col]
X

go  until  jurong  point  crazy  available  only  in  bugis  n  ...  \
0      1      1       1      1      1          1     1   1      1  1  ...   
1      0      0       0      0      0          0     0   0      0  0  ...   
2      0      0       0      0      0          0     0   1      0  0  ...   
3      0      0       0      0      0          0     0   0      0  0  ...   
4      0      0       0      0      0          0     0   0      0  0  ...   
...   ..    ...     ...    ...    ...        ...   ...  ..    ... ..  ...   
5567   0      0       0      0      0          0     1   0      0  0  ...   
5568   0      0       0      0      0          0     0   0      0  0  ...   
5569   0      0       0      0      0          0     0   1      0  0  ...   
5570   0      0       0      0      0          0     0   1      0  0  ...   
5571   0      0       0      0      0          0     0   0      0  0  ...   

      heap  lowes  salesman  å£750  087187272008  now1  pity  soany  \
0        0      0         0      0             0     0     0      0   
1        0      0         0      0             0     0     0      0   
2        0      0         0      0             0     0     0      0   
3        0      0         0      0             0     0     0      0   
4        0      0         0      0             0     0     0      0   
...    ...    ...       ...    ...           ...   ...   ...    ...   
5567     0      0         0      1             1     1     0      0   
5568     0      0         0      0             0     0     0      0   
5569     0      0         0      0             0     0     1      1   
5570     0      0         0      0             0     0     0      0   
5571     0      0         0      0             0     0     0      0   

      suggestions  bitching  
0               0         0  
1               0         0  
2               0         0  
3               0         0  
4               0         0  
...           ...       ...  
5567            0         0  
5568            0         0  
5569            1         0  
5570            0         1  
5571            0         0  

[5572 rows x 9877 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((3900, 9877), (3900,), (1672, 9877), (1672,))

In [8]:
clf = MultinomialNB()
clf.fit(X_train, y_train)

MultinomialNB()

In [9]:
clf.predict_proba(X_test)

array([[9.99999849e-01, 1.51325499e-07],
       [9.99998545e-01, 1.45450430e-06],
       [1.00000000e+00, 1.99572171e-37],
       ...,
       [9.99976501e-01, 2.34987279e-05],
       [9.99807717e-01, 1.92282736e-04],
       [9.99818705e-01, 1.81295241e-04]])

In [10]:
y_pred = clf.predict(X_test)
y_pred

array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype='<U4')

In [11]:
scores = cross_val_score(clf, X, y, scoring="accuracy", cv=10)
scores

array([0.98387097, 0.97670251, 0.98025135, 0.97845601, 0.97486535,
       0.97486535, 0.97127469, 0.98025135, 0.96947935, 0.98204668])

In [12]:
accuracy_score(y_test, y_pred)

0.9760765550239234

In [13]:
confusion_matrix(y_test, y_pred)

array([[1418,   25],
       [  15,  214]])