<a href="https://colab.research.google.com/github/smenaaliaga/Magister/blob/master/Tarea_5_mayo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Estudio sobre Numpy

In [0]:
import numpy as np

In [0]:
d = np.array([0.10,1.01,0.87,1.15])
d

array([0.1 , 1.01, 0.87, 1.15])

In [4]:
np.random.rand(10)

array([0.6239746 , 0.79326304, 0.24202129, 0.47603124, 0.37157055,
       0.89737269, 0.24877031, 0.81019625, 0.42381051, 0.61192605])

In [6]:
np.random.randint(5, size=10)

array([4, 1, 0, 3, 1, 1, 2, 1, 0, 2])

In [7]:
np.random.rand(5,5)

array([[0.36697489, 0.86763806, 0.52035559, 0.55373461, 0.41004846],
       [0.34214626, 0.99797798, 0.40678998, 0.54530956, 0.37350859],
       [0.78488866, 0.81512723, 0.32976217, 0.78998721, 0.2711829 ],
       [0.20031115, 0.55387412, 0.63398507, 0.35079289, 0.66296762],
       [0.0867747 , 0.61955415, 0.57730682, 0.28989092, 0.78104825]])

In [12]:
# Guardar vector
A = np.random.rand(6)
A

array([0.92012606, 0.55249623, 0.68251173, 0.54802848, 0.70223047,
       0.30023923])

In [13]:
# Obtener una posición del vecotr
A[0]

0.9201260560547986

In [16]:
# Guardar una matriz
A = np.random.rand(5,5)
A

array([[0.88807858, 0.07603903, 0.05599571, 0.78503521, 0.39758466],
       [0.55260775, 0.77736437, 0.07283086, 0.38379371, 0.09126811],
       [0.0476451 , 0.25996577, 0.14625926, 0.50300847, 0.27519058],
       [0.83868379, 0.13061946, 0.01491973, 0.94141166, 0.13855648],
       [0.30659891, 0.77320317, 0.93796956, 0.31253441, 0.03515974]])

In [17]:
# Obtener rebanada entre fila 0 y 2 y las columnas 1 y 3
A[0:2,1:3]

array([[0.07603903, 0.05599571],
       [0.77736437, 0.07283086]])

In [18]:
# Obtener toda las filas de la segunda columna
A[:,1]

array([0.07603903, 0.77736437, 0.25996577, 0.13061946, 0.77320317])

In [19]:
# Suma de filas o columnas. axis = 1: filas, 0: columnas
np.sum(A, axis=1)

array([2.20273319, 1.8778648 , 1.23206919, 2.06419112, 2.36546578])

# Enunciado

Si cuenta con n vectores de m dimensiones cada uno, todos representando una matriz X, que tiene naturalmente m filas y n columnas. ¿Cómo podría calcular la distancia de todos contra todos?


*   Intente realizar con una matriz aleatoria
*   Reflexione primero que dimensión tiene que tener la matriz que tiene todas las distancias
